spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel
        goal_completed_channel:
          name: goal_completed_topic
        recommendation_chanel:
          name: recommendation_channel
        mentorship_channel:
           name: mentorship_channel

server:
  port: 8088

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

minio:
  endpoint: http://localhost:9000
  user: user
  password: password
  bucketName: corpbucket
  picGeneratorUrl: https://api.dicebear.com/6.x/initials/svg?seed=
  picType: &radius=20&backgroundType=gradientLinear

aws:
  accessKey: access_key
  secretKey: secret_key
  region: bucket_region

services:
  s3:
    bucket-name: user_bucket
    isMocked: true
    endpoint: <http://localhost:9000>
    accessKey: user
    secretKey: password
    bucketName: projectbucket
