ALTER TABLE users
ADD COLUMN IF NOT EXISTS created_by VARCHAR(64),
ADD COLUMN IF NOT EXISTS updated_by VARCHAR(64),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS version    BIGINT,
ADD COLUMN IF NOT EXISTS name       VARCHAR(64),
ADD COLUMN IF NOT EXISTS surname    VARCHAR(64);

